INSERT INTO categoria (nome) VALUES
("Desenvolvimento Web"),
("Banco de Dados"),
("Inteligência Artificial"),
("Programação Mobile"),
("Segurança da Informação"),
("DevOps"),
("Cloud Computing"),
("Internet das Coisas (IoT)"),
("Desenvolvimento de Jogos"),
("Big Data & Analytics"),
("Machine Learning"),
("Blockchain"),
("Arquitetura de Software"),
("Engenharia de Software"),
("UI/UX Design"),
("Frameworks Frontend"),
("Frameworks Backend"),
("APIs e Integrações"),
("Microservices"),
("Programação Funcional"),
("Programação Orientada a Objetos"),
("Automação de Testes"),
("Performance e Escalabilidade"),
("Edge Computing"),
("Realidade Aumentada e Virtual"),
("Chatbots e Assistentes Virtuais"),
("Low-Code e No-Code"),
("Desenvolvimento de APIs REST e GraphQL"),
("Segurança em Aplicações Web"),
("Gestão de Projetos de Software");


INSERT INTO artigo (titulo, conteudo, id_cat) VALUES
("Introdução ao HTML5", "O HTML5 trouxe diversas melhorias para a estruturação de páginas web...", (SELECT id_cat FROM categoria WHERE nome = "Desenvolvimento Web")),
("CSS Flexbox e Grid", "Aprenda a criar layouts modernos com Flexbox e Grid...", (SELECT id_cat FROM categoria WHERE nome = "Desenvolvimento Web")),
("JavaScript: Fundamentos Essenciais", "Entenda os conceitos básicos da linguagem que domina a web...", (SELECT id_cat FROM categoria WHERE nome = "Desenvolvimento Web")),
("Banco de Dados Relacional vs NoSQL", "Comparação entre bancos SQL e NoSQL e quando usar cada um...", (SELECT id_cat FROM categoria WHERE nome = "Banco de Dados")),
("REST vs GraphQL: Qual escolher?", "Entenda as diferenças entre essas tecnologias de APIs...", (SELECT id_cat FROM categoria WHERE nome = "APIs e Integrações")),
("Introdução ao Node.js", "O que é Node.js e por que ele é tão popular no desenvolvimento backend...", (SELECT id_cat FROM categoria WHERE nome = "APIs e Integrações")),
("Autenticação com JWT no PHP", "Como implementar autenticação segura com JSON Web Tokens...", (SELECT id_cat FROM categoria WHERE nome = "Segurança em Aplicações Web")),
("Laravel: Primeiros Passos", "Configurando e criando um projeto no Laravel do zero...", (SELECT id_cat FROM categoria WHERE nome = "Frameworks Backend")),
("Vue.js: Criando um SPA", "Guia passo a passo para desenvolver uma Single Page Application...", (SELECT id_cat FROM categoria WHERE nome = "Frameworks Frontend")),
("React vs Angular: Qual escolher?", "Comparação entre os dois frameworks mais populares do frontend...", (SELECT id_cat FROM categoria WHERE nome = "Frameworks Frontend")),
("Segurança em Aplicações Web", "Dicas para proteger sua aplicação contra ataques comuns...", (SELECT id_cat FROM categoria WHERE nome = "Segurança em Aplicações Web")),
("Docker para Desenvolvedores", "Aprenda a criar e gerenciar containers com Docker...", (SELECT id_cat FROM categoria WHERE nome = "DevOps")),
("Microservices com Spring Boot", "Como estruturar um sistema baseado em microsserviços...", (SELECT id_cat FROM categoria WHERE nome = "Microservices")),
("Testes Automatizados com Jest", "Melhores práticas para testar código JavaScript com Jest...", (SELECT id_cat FROM categoria WHERE nome = "Automação de Testes")),
("Machine Learning com Python", "Introdução ao aprendizado de máquina utilizando Python...", (SELECT id_cat FROM categoria WHERE nome = "UI/UX Design")),
("Criando um Chatbot com IA", "Passo a passo para desenvolver um chatbot inteligente...", (SELECT id_cat FROM categoria WHERE nome = "Chatbots e Assistentes Virtuais")),
("O que é Blockchain?", "Entenda a tecnologia por trás do Bitcoin e outras criptomoedas...", (SELECT id_cat FROM categoria WHERE nome = "Blockchain")),
("Big Data: O que você precisa saber", "Principais conceitos e ferramentas para análise de Big Data...", (SELECT id_cat FROM categoria WHERE nome = "Big Data & Analytics")),
("Desenvolvendo APIs com FastAPI", "Como criar APIs rápidas e eficientes com FastAPI...", (SELECT id_cat FROM categoria WHERE nome = "APIs e Integrações")),
("NoSQL com MongoDB", "Introdução ao banco de dados NoSQL MongoDB...", (SELECT id_cat FROM categoria WHERE nome = "Banco de Dados")),
("GraphQL na Prática", "Como utilizar GraphQL para criar APIs eficientes...", (SELECT id_cat FROM categoria WHERE nome = "APIs e Integrações")),
("Kubernetes para Iniciantes", "Gerenciando containers em escala com Kubernetes...", (SELECT id_cat FROM categoria WHERE nome = "DevOps")),
("Scrum e Metodologias Ágeis", "Entenda como funciona o Scrum e as práticas ágeis...", (SELECT id_cat FROM categoria WHERE nome = "Gestão de Projetos de Software")),
("Desenvolvimento Mobile com Flutter", "Criando aplicativos multiplataforma com Flutter...", (SELECT id_cat FROM categoria WHERE nome = "Programação Mobile")),
("IoT: Internet das Coisas", "Explorando o mundo da Internet das Coisas...", (SELECT id_cat FROM categoria WHERE nome = "Internet das Coisas (IoT)")),
("Cybersecurity: Como se proteger online", "Boas práticas para aumentar a segurança na internet...", (SELECT id_cat FROM categoria WHERE nome = "Segurança da Informação")),
("Criando um E-commerce do zero", "Passos essenciais para desenvolver uma loja virtual...", (SELECT id_cat FROM categoria WHERE nome = "Desenvolvimento Web"));



INSERT INTO usuario (nome, email, data_nasc, cpf, telefone) VALUES
('Ana Souza', 'ana.souza@email.com', '1990-05-12', '12345678901', '67999990001'),
('Carlos Silva', 'carlos.silva@email.com', '1985-07-25', '23456789012', '67999990002'),
('Mariana Lima', 'mariana.lima@email.com', '1993-09-14', '34567890123', '67999990003'),
('Fernando Alves', 'fernando.alves@email.com', '1992-11-30', '45678901234', '67999990004'),
('Juliana Castro', 'juliana.castro@email.com', '1995-06-22', '56789012345', '67999990005'),
('Pedro Henrique', 'pedro.henrique@email.com', '1988-08-19', '67890123456', '67999990006'),
('Laura Mendes', 'laura.mendes@email.com', '1991-12-05', '78901234567', '67999990007'),
('Thiago Rocha', 'thiago.rocha@email.com', '1986-04-28', '89012345678', '67999990008'),
('Camila Nunes', 'camila.nunes@email.com', '1994-03-15', '90123456789', '67999990009'),
('Gabriel Costa', 'gabriel.costa@email.com', '1989-10-07', '01234567890', '67999990010'),
('Beatriz Ferreira', 'beatriz.ferreira@email.com', '1996-02-21', '12345098765', '67999990011'),
('Lucas Martins', 'lucas.martins@email.com', '1990-09-18', '23456098765', '67999990012'),
('Vanessa Oliveira', 'vanessa.oliveira@email.com', '1993-11-08', '34567098765', '67999990013'),
('Rafael Borges', 'rafael.borges@email.com', '1987-05-14', '45678098765', '67999990014'),
('Patrícia Almeida', 'patricia.almeida@email.com', '1992-07-27', '56789098765', '67999990015'),
('Rodrigo Teixeira', 'rodrigo.teixeira@email.com', '1994-01-05', '67890098765', '67999990016'),
('Carolina Santos', 'carolina.santos@email.com', '1989-06-12', '78901098765', '67999990017'),
('Diego Moreira', 'diego.moreira@email.com', '1995-08-22', '89012098765', '67999990018'),
('Larissa Pinto', 'larissa.pinto@email.com', '1991-04-30', '90123098765', '67999990019'),
('Felipe Rezende', 'felipe.rezende@email.com', '1986-12-07', '01234098765', '67999990020'),
('Tatiane Barbosa', 'tatiane.barbosa@email.com', '1990-02-25', '12345087654', '67999990021'),
('André Luiz', 'andre.luiz@email.com', '1985-11-17', '23456087654', '67999990022'),
('Natália Cardoso', 'natalia.cardoso@email.com', '1993-03-09', '34567087654', '67999990023'),
('Eduardo Lima', 'eduardo.lima@email.com', '1988-07-20', '45678087654', '67999990024'),
('Sabrina Rocha', 'sabrina.rocha@email.com', '1994-05-18', '56789087654', '67999990025');
